project:
  type: website

website:
  title: "Advanced illustration options"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Overview"
        href: index.md
      - section: "Lecture slides"
        contents:
          - slides.md
      - section: "Lab practicals"
        contents:
          - practicals.md  
      - section: "interactive graphs"
        contents: 
          - interactive_graphs.qmd
      - section: "genome visualization"
        contents:
          - genome_visualization.qmd
        

format: 
  html:
    code-fold: true
    code-summary: "Click here to show the code"
    code-tools: true
    theme: 
      - solar
    self-contained: true
    page-layout: full
    toc: true
    toc-depth: 3
    css: styles.css
    include-in-header:
      - file: github-corner.html
# engine: knitr

execute:
  freeze: auto
